store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-4'


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-4'


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'readonly': True}))
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'image')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class']= 'custom-file-input'

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from products.models import Basket


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегестрировались!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm
    context = {'form': form}
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=user)
    baskets = Basket.objects.filter(user=user)
    total_quantity = sum(basket.quantity for basket in baskets)
    total_sum = sum(basket.sum() for basket in baskets)
    context = {
        'form': form, 'title': 'Store - Личный кабинет',
        'baskets': baskets,
        'total_quantity': total_quantity,
        'total_sum': total_sum
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Авторизация</title>
    <link href="{% static 'css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="col-lg-5">
        {% if messages or form.errors %}
            <div class="alert
             {% if messages %} alert-success {% else %} alert-warning {% endif %}
              alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {{ form.non_field_errors }}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a class="small" href="#">Забыли пароль?</a>
                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            {% include 'products/basket.html' %}
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="col-lg-7">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{ form.errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                                почты</label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                    пароля</label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
{% endblock %}